apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rs-app
  template:
    metadata:
      labels:
        app: rs-app
    spec:
      containers:
        - name: app
          image: nginx
          resources:
            limits:      
              cpu: "300m"
              memory: "256Mi"
