apiVersion: batch/v1
kind: Job
metadata:
  name: report-generator
spec:
  template:
    spec:
      containers:
      - name: report-generator
        image: bash
        command: ["bash", "-c", "echo 'Report generation done'"]
      restartPolicy: Never
