apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
---
# After deploying the test pod, students should execute the following commands to verify connectivity:
# 1. Get the pod's IP address kubectl get pod test-pod -o wide
# 2. From another node, run a ping test to the test pod's
# ping <test-pod-ip>
# 3. kubectl desceribe pod test-pod -o yml > test-pod-description.yaml




