apiVersion: v1
kind: Pod
metadata:
  name: sidecar-app
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - name: shared
          mountPath: /data
    - name: logger
      image: busybox
      command: ["sh", "-c", "tail -f /data"]
  volumes:
    - name: shared
      emptyDir: {}
  initContainers:
    - name: init-downloader
      image: busybox
      command: ["sh", "-c", "echo 'Initial data downloaded' > /data/index.html"]
      volumeMounts:
        - name: shared
          mountPath: /data
